version: "3.8"

services:
  express:
    build: .
    container_name: express-app
    expose:
      - "3000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

